package templates

const (
	FetchSelectionJobs = `
		SELECT S.ID AS SUBMISSION_ID,
			   SOLUTION,
			   REFERENCE_SOLUTION,
			   SCHEMA_NAME,
			   CHECK_ORDER
		FROM SUBMISSION S
		JOIN TASK T ON S.TASK_ID = T.ID
		JOIN SELECTION_TASK ST ON T.ID = ST.TASK_ID
		WHERE SUBMISSION_STATUS_ID = 1 AND T.TASK_TYPE = 'SELECTION'
	`
	FetchTaskRestrictions = `
		SELECT R.NAME
		FROM TASK_RESTRICTION TR
		JOIN RESTRICTION R ON TR.RESTRICTION_ID = R.ID
		WHERE TR.TASK_ID = (
			SELECT TASK_ID
			FROM SUBMISSION
			WHERE ID = :1
		)
	`
	ReviewSelectionContent = `
		WITH SOLUTION_RESULT AS (%[1]s), REFERENCE_RESULT AS (%[2]s)
		SELECT * FROM SOLUTION_RESULT
		MINUS
		SELECT * FROM REFERENCE_RESULT
		UNION ALL
		SELECT * FROM REFERENCE_RESULT
		MINUS
		SELECT * FROM SOLUTION_RESULT
	`
	ReviewSelectionOrder = `
		WITH SOLUTION_RESULT AS (%[1]s), REFERENCE_RESULT AS (%[2]s)
		SELECT SOLUTION_RESULT.*, ROWNUM FROM SOLUTION_RESULT
		MINUS
		SELECT REFERENCE_RESULT.*, ROWNUM FROM REFERENCE_RESULT
		UNION ALL
		SELECT REFERENCE_RESULT.*, ROWNUM FROM REFERENCE_RESULT
		MINUS
		SELECT SOLUTION_RESULT.*, ROWNUM FROM SOLUTION_RESULT
	`
	UpdateSubmissionReviewInfo = `
		UPDATE SUBMISSION
		SET SUBMISSION_STATUS_ID = :1,
			REVIEWER_MESSAGE = :2
		WHERE ID = :3
	`
)
